import { Inter, Noto_Kufi_Arabic } from "next/font/google";
import "../globals.css";
import Header from "@/components/Header";
import GlobalProviders from "@/components/GlobalProviders";
import Footer from "@/components/Footer";
import { NextIntlClientProvider } from "next-intl";
import {getMessages} from 'next-intl/server';
import { Toaster } from "@/components/ui/toaster";
const inter = Inter({ subsets: ["latin"] ,
  weight: ['300', '400', '500', '600', '700']});

const fontArab = Noto_Kufi_Arabic({
  subsets: ['arabic'],
  variable: '--ff-primary',
  weight: ['300', '400', '500', '600', '700']
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; 

export default async function RootLayout({
  children,
  params: { session, ...params },
}) {
  const messages = await getMessages();
  return (
    <html lang="en">
      <body className={inter.className}>
      <NextIntlClientProvider messages={messages}>
        <GlobalProviders session={session}>
            <Header />
            {children}
            <Footer/>
            <Toaster />
        </GlobalProviders>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
