export const OFFER_CATEGORIES_SLIDER="offer_slider_widget"
export const BANNER_SLIDER="offer_slider_widget"
export const CATEGORIES_SLIDER="popular_categories"
export const PRODUCTS_SLIDER="product_slider_widget"
export const OFFER_SLIDER="category_sec_banner"
export const BUDGET_SLIDER="top_categories"