import { Inter } from "next/font/google";
import "../../style/global.scss";
import Header from "@/widgets/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LocaleLayout({ children,auth, params: {locale} }) {
  return (
    <html  lang={locale}>
      <body className={inter.className}>
        
        <Header/>
        {children}<div>{auth}</div></body>
    </html>
  );
}